name: FastAPI CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: vivek342/fastapi-api

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Image
      working-directory: task1 docker builds
      run: docker build -t $IMAGE_NAME:latest .
  
    - name: Push Image
      run: docker push $IMAGE_NAME:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config

    - name: Verify Cluster
      run: |
        kubectl config current-context
        kubectl get nodes

    - name: Deploy
      working-directory: task3 kubernetes
      run: |
        kubectl apply -f secrets.yml
        kubectl apply -f config.yml
        kubectl apply -f hpa.yml
        kubectl apply -f deployments.yml
        kubectl apply -f LoadBalancer.yml
        
