name: FastAPI CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME:  vivek342/fastapi-api
  
jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Docker Login
    #   run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Image
      run: docker buildx build --load -t $IMAGE_NAME:latest .

    - name: Push Image
      run: docker push $IMAGE_NAME

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig

    - name: Deploy
      run: |
        export KUBECONFIG=kubeconfig
        kubectl apply -f k8s/
